### PR TITLE
Better idempotency

### LINKED ISSUE #78: Upgrade failure not resumable after node creation timed out
While performing an upgrade of a cluster with a 3 node control plane, the cluster upgrade tool timed out while waiting for a new machine. The error message is below:

```
Error: timed out waiting for matching node: timed out waiting for the condition
timed out waiting for the condition
timed out waiting for matching node
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*MachineCreator).waitForMatchingNode
        /workspace/pkg/upgrade/machine_creator.go:198
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*MachineCreator).NewMachine
        /workspace/pkg/upgrade/machine_creator.go:121
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).updateMachines
        /workspace/pkg/upgrade/control_plane.go:295
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).Upgrade
        /workspace/pkg/upgrade/control_plane.go:101
main.upgradeCluster
        /workspace/main.go:113
main.main.func1
        /workspace/main.go:37
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main
        /workspace/main.go:81
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

The problem is that I'm unable to resume this failed upgrade. After this failure, every subsequent run will also fail with the following error:

```
time="2019-10-02T17:43:33Z" level=info msg="Updating provider IDs to nodes"
time="2019-10-02T17:43:33Z" level=info msg="etcdctl stdout: {\"header\":{\"cluster_id\":12274807018475341212,\"member_id\":5631729273476060830,\"raft_term\":12},\"members\":[{\"ID\":5631729273476060830,\"name\":\"ip-10-0-1-221.us-west-2.compute.internal\",\"peerURLs\":[\"https://10.0.1.221:2380\"],\"clientURLs\":[\"https://10.0.1.221:2379\"]},{\"ID\":9383203200922539889,\"name\":\"ip-10-0-5-216.us-west-2.compute.internal\",\"peerURLs\":[\"https://10.0.5.216:2380\"],\"clientURLs\":[\"https://10.0.5.216:2379\"]},{\"ID\":13814063600145251805,\"name\":\"ip-10-0-3-16.us-west-2.compute.internal\",\"peerURLs\":[\"https://10.0.3.16:2380\"],\"clientURLs\":[\"https://10.0.3.16:2379\"]}]}\n"
time="2019-10-02T17:43:33Z" level=info msg="etcdctl stderr: "
time="2019-10-02T17:43:33Z" level=info msg="Couldn't retrieve oldNode" id="aws:////i-07af0e8f5bd13d4aa"
unknown previous node "aws:////i-07af0e8f5bd13d4aa"
Error: unknown previous node "aws:////i-07af0e8f5bd13d4aa"
```

Full logs are below: 

[phase1-ajw-upgrade-ha-68vfr.log](https://github.com/vmware/cluster-api-upgrade-tool/files/3686908/phase1-ajw-upgrade-ha-68vfr.log)
[phase1-ajw-upgrade-ha-2dx4s.log](https://github.com/vmware/cluster-api-upgrade-tool/files/3686909/phase1-ajw-upgrade-ha-2dx4s.log)

The following arguments were passed to the upgrade tools:

```
        - --kubernetes-version=1.15.3
        - --scope=control-plane
        - --cluster-name=ajw-upgrade-ha
        - --cluster-namespace= 2af7b66e2668ce0283f346968cbd71c986ed9fab
        - --kubeconfig-secret=ajw-upgrade-ha-kubeconfig
        - --upgrade-id=ajw-upgrade-ha-phase1
```

### LINKED ISSUE #79: Machines are not cleaned up on failure causing extra control plane/etcd members
If an upgrade fails after a machine is created, the machine is not cleaned up and may ultimately join the cluster. Attaching logs from four upgrade attempts on a three node control plane cluster. Ultimately I ended up with an etcd cluster that had 6 members. I unfortunately lost the output of `kubectl get nodes` due to a laptop restart but there were also >= 6 control plane nodes.

Attaching all of the logs but example is below:

```
time="2019-09-19T23:13:33Z" level=info msg="Updating provider IDs to nodes"
time="2019-09-19T23:13:33Z" level=info msg=deleteEtcdMember
time="2019-09-19T23:13:37Z" level=info msg="etcdctl stdout: "
time="2019-09-19T23:13:37Z" level=info msg="etcdctl stderr: Error: member ID is not provided\n"
Error: unable to delete old etcd member : command terminated with exit code 128
command terminated with exit code 128
github.com/vmware/cluster-api-upgrade-tool/pkg/internal/kubernetes.PodExec
        /workspace/pkg/internal/kubernetes/pod_exec.go:63
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).etcdctlForPod
        /workspace/pkg/upgrade/control_plane.go:525
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).deleteEtcdMember
        /workspace/pkg/upgrade/control_plane.go:469
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).updateMachines
        /workspace/pkg/upgrade/control_plane.go:307
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).Upgrade
        /workspace/pkg/upgrade/control_plane.go:101
main.upgradeCluster
        /workspace/main.go:114
main.main.func1
        /workspace/main.go:37
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main
        /workspace/main.go:82
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
unable to delete old etcd member
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).updateMachines
        /workspace/pkg/upgrade/control_plane.go:309
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).Upgrade
        /workspace/pkg/upgrade/control_plane.go:101
main.upgradeCluster
        /workspace/main.go:114
main.main.func1
        /workspace/main.go:37
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main
        /workspace/main.go:82
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

Etcd members:
```
$ k exec -ti -n kube-system etcd-ip-10-0-3-111.us-west-2.compute.internal -- etcdctl --ca-file=/etc/kubernetes/pki/etcd/ca.crt --key-file=/etc/kubernetes/pki/etcd/peer.key --cert-file=/etc/kubernetes/pki/etcd/peer.crt --endpoints=https://127.0.0.1:2379 cluster-health
member 3285a671bb2f9595 is healthy: got healthy result from https://10.0.5.84:2379
member 5ed3ed67c9a1e4e3 is healthy: got healthy result from https://10.0.5.239:2379
member c2c953e2269e5dab is healthy: got healthy result from https://10.0.5.55:2379
member c6d9414aef83f711 is healthy: got healthy result from https://10.0.5.120:2379
member f051abf97498a9af is healthy: got healthy result from https://10.0.1.123:2379
member fd3298bb7c4dd093 is healthy: got healthy result from https://10.0.3.111:2379
cluster is healthy
```

[pod_phase1-ajw3-6plzz-logs.txt](https://github.com/vmware/cluster-api-upgrade-tool/files/3687044/pod_phase1-ajw3-6plzz-logs.txt)
[pod_phase1-ajw3-tfblx-logs.txt](https://github.com/vmware/cluster-api-upgrade-tool/files/3687045/pod_phase1-ajw3-tfblx-logs.txt)
[pod_phase1-ajw3-w24qh-logs.txt](https://github.com/vmware/cluster-api-upgrade-tool/files/3687046/pod_phase1-ajw3-w24qh-logs.txt)
[pod_phase1-ajw3-zlrcz-logs.txt](https://github.com/vmware/cluster-api-upgrade-tool/files/3687047/pod_phase1-ajw3-zlrcz-logs.txt)

### LINKED ISSUE #81: Make new machine names configurable
https://github.com/vmware/cluster-api-upgrade-tool/pull/72/files#r331532807

Currently the machine names are set like this `name := fmt.Sprintf("%s-%s-%d", nameParts[0], nameParts[1], time.Now().Unix())`.

### LINKED ISSUE #83: Use cluster-api patch helper
See: https://github.com/vmware/cluster-api-upgrade-tool/pull/72/files#r331558465

Currently patches are made with using the raw controller runtime. Replace those patches with the cluster-api helper.

### LINKED ISSUE #85: Update secret owner reference once
The secret needs to be updated just once when the initial control plane is replaced. Currently its being updated for every control plane that's replaced.

### PR DESCRIPTION
**Pull request by ncdc**
Make the control plane upgrade process as reentrant as possible. Check for the existence of objects we would be creating before trying to create them.

Fixes #78 
Fixes #79
Fixes #81
Fixes #83
Fixes #85

### CODE REVIEW

File: pkg/upgrade/control_plane.go [hunk 1]
```diff
@@ -343,144 +395,245 @@ func (u *ControlPlaneUpgrader) updateMachine(name string, machine clusterv1.Mach
...
+			log.Info("Skipping machine as it is a replacement machine for the in-process upgrade")
 			continue
 		}
 
-		// assume the original name is controlplane-<index> or controlplane-<index>-<timestamp>
-		// let's set the new name to controlplane-<index>-<timestamp>
-		nameParts := strings.Split(machine.Name, "-")
-		if len(nameParts) < 2 {
-			return errors.Errorf("machine name %q does not match expected format <name>-<index> or <name>-<index>-<timestamp>", machine.Name)
+		// Skip if we've already completed this machine
```
Comment (ncdc) [inline pkg/upgrade/control_plane.go]: I'm not sure if this is relevant. If we're upgrading an original machine _O_, it will have the upgrade-id annotation, but we only ever apply the completed annotation to the replacement machine _R_. When we complete the upgrade of _O_, we delete it. When we complete the upgrade of the entire control plane, we remove all upgrade-tool annotations from all the replacement machines. WDYT @chuckha?

File: pkg/upgrade/control_plane.go [hunk 2]
```diff
@@ -815,3 +1015,121 @@ func (u *ControlPlaneUpgrader) UpdateProviderIDsToNodes() error {
...
+	var matchingNode v1.Node
+	providerID, err := noderefutil.NewProviderID(rawProviderID)
+	if err != nil {
+		return nil, err
+	}
+
+	err = wait.PollImmediate(5*time.Second, timeout, func() (bool, error) {
+		nodes, err := u.targetKubernetesClient.CoreV1().Nodes().List(metav1.ListOptions{})
+		if err != nil {
+			return false, err
```
Comment (ncdc) [inline pkg/upgrade/control_plane.go]: Same question here re `err` vs `timeout`

File: pkg/upgrade/control_plane.go (hunk 1 above)
Comment (chuckha) [reply pkg/upgrade/control_plane.go]: hmm, I was thinking we'd apply the completed annotations to the original machine so we could skip it at this point since we already filter out replacement machines from "list of machines that need upgrades"

File: pkg/upgrade/control_plane.go [hunk 3]
```diff
@@ -815,3 +1015,121 @@ func (u *ControlPlaneUpgrader) UpdateProviderIDsToNodes() error {
...
 	return nil
 }
+
+func (u *ControlPlaneUpgrader) waitForProviderID(ns, name string, timeout time.Duration) (string, error) {
+	u.log.Info("waitForMachineProviderID start", "namespace", ns, "name", name)
+	var providerID string
+	err := wait.PollImmediate(5*time.Second, timeout, func() (bool, error) {
+		machine := &clusterv1.Machine{}
+		if err := u.managementClusterClient.Get(context.TODO(), ctrlclient.ObjectKey{Name: name, Namespace: ns}, machine); err != nil {
+			return false, errors.WithStack(err)
```
[the remark this answers is not in the document]
Comment (chuckha) [reply pkg/upgrade/control_plane.go]: Is this related to https://github.com/vmware/cluster-api-upgrade-tool/issues/96 ?

[the remark this answers is not in the document]
Comment (chuckha) [reply pkg/upgrade/control_plane.go]: +1 to logging the error though to get to the full timeout.

File: pkg/upgrade/control_plane.go (hunk 2 above)
Comment (chuckha) [reply pkg/upgrade/control_plane.go]: again yes, logging the error is better than bailing early.

Comment (chuckha) [reply pkg/upgrade/control_plane.go]: I am ok with follow up issues too, we don't have to get everything into this PR. It's already pretty massive.

File: pkg/upgrade/control_plane.go (hunk 1 above)
Comment (ncdc) [reply pkg/upgrade/control_plane.go]: Given that everything is idempotent now, we'd be inserting a step to annotate the machine as completed in between deleting it from etcd, and deleting the machine itself. I don't think it's worth it? If we don't manage to delete a machine but everything else before that succeeds, the next time we run the tool, it'd be a no-op until we get to the machine deletion part. Right?

File: pkg/upgrade/control_plane.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (ncdc) [reply pkg/upgrade/control_plane.go]: It's possible it's related. I saw issues with the capd/nginx load balancer where every 4th request would fail (3 original machines + 1 new machine that hadn't finished bootstrapping).

[the remark this answers is not in the document]
Comment (chuckha) [reply pkg/upgrade/control_plane.go]: seems like there isn't much we can do about it from this side (upgrade tool) except your suggested fix

File: pkg/upgrade/control_plane.go (hunk 1 above)
Comment (chuckha) [reply pkg/upgrade/control_plane.go]: ugh, my fault. This stuff is hard to rebuild context around.

Yeah, you're right, I agree this section isn't relevant then.
