### PR TITLE
fix: remove old nodes from kubeadm configmap

### LINKED ISSUE #59: Update kubeadm configmap
When we remove a node we should remove it from the kubeadm config or risk etc attempting to contact a no longer responsive endpoint.

### PR DESCRIPTION
**Pull request by rudoi**
Fixes #59

### CODE REVIEW

File: pkg/upgrade/control_plane.go [hunk 1]
```diff
@@ -419,6 +426,7 @@ func (u *ControlPlaneUpgrader) updateBootstrapConfig(name string, machine *clust
 		}
 	}
 	bootstrap.Spec.JoinConfiguration.NodeRegistration = nodeRegistration
+	bootstrap.Spec.JoinConfiguration.Discovery.BootstrapToken = &kubeadmv1beta1.BootstrapTokenDiscovery{}
```
Comment (amy) [inline pkg/upgrade/control_plane.go]: Is there an existing one to copy over?

File: pkg/upgrade/control_plane.go [hunk 2]
```diff
@@ -277,6 +278,10 @@ func (u *ControlPlaneUpgrader) updateMachine(name string, machine clusterv1.Mach
 		return err
 	}
 
+	if err := u.applyAnnotation(newMachine); err != nil {
```
Comment (rudoi) [inline pkg/upgrade/control_plane.go]: I found most errors to show up during machine deletion / etcd member removal, so I put the annotation before those steps so that resuming would work.

Comment (rudoi) [reply pkg/upgrade/control_plane.go]: Though, you do still end up with an orphaned machine in either case.

File: pkg/upgrade/control_plane.go (hunk 1 above)
Comment (chuckha) [reply pkg/upgrade/control_plane.go]: the problem with copying it over is that it's probably expired. Clearing it like this will generate a new one that won't be expired

File: pkg/upgrade/control_plane.go [hunk 3]
```diff
@@ -24,6 +24,7 @@ import (
 	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
 	bootstrapv1 "sigs.k8s.io/cluster-api-bootstrap-provider-kubeadm/api/v1alpha2"
 	kubeadmv1beta1 "sigs.k8s.io/cluster-api-bootstrap-provider-kubeadm/kubeadm/v1beta1"
+	kubeadmv1beta2 "sigs.k8s.io/cluster-api-bootstrap-provider-kubeadm/kubeadm/v1beta2"
```
Comment (ncdc) [inline pkg/upgrade/control_plane.go]: Do you need v1beta2 specifically? It looks like the ClusterStatus type is the same in both versions?

File: pkg/upgrade/control_plane.go [hunk 4]
```diff
@@ -700,3 +726,23 @@ func updateKubeadmKubernetesVersion(original *v1.ConfigMap, version string) (*v1
 
 	return cm, nil
 }
+
+func removeNodeFromClusterStatus(original *v1.ConfigMap, nodeName string) (*v1.ConfigMap, error) {
+	cm := original.DeepCopy()
+
+	clusterStatus := &kubeadmv1beta2.ClusterStatus{}
+	if err := yaml.Unmarshal([]byte(cm.Data["ClusterStatus"]), &clusterStatus); err != nil {
```
[the remark this answers is not in the document]
Comment (rudoi) [reply pkg/upgrade/control_plane.go]: Definitely, will fix. though we have other problems if this field is unset :D

File: pkg/upgrade/control_plane.go [hunk 5]
```diff
@@ -700,3 +726,23 @@ func updateKubeadmKubernetesVersion(original *v1.ConfigMap, version string) (*v1
 
 	return cm, nil
 }
+
+func removeNodeFromClusterStatus(original *v1.ConfigMap, nodeName string) (*v1.ConfigMap, error) {
+	cm := original.DeepCopy()
+
+	clusterStatus := &kubeadmv1beta2.ClusterStatus{}
```
Comment (chuckha) [inline pkg/upgrade/control_plane.go]: we're using v1beta1 types from CABPK, is there any reason you imported v1beta2 instead?

File: pkg/upgrade/control_plane.go [hunk 6]
```diff
@@ -681,6 +689,24 @@ func (u *ControlPlaneUpgrader) updateAndUploadKubeadmKubernetesVersion() error {
...
+	if err != nil {
+		return errors.Wrap(err, "error getting kubeadm configmap from target cluster")
+	}
+
+	updated, err := removeNodeFromClusterStatus(original, nodeName)
+	if err != nil {
+		return err
+	}
+
+	if _, err = u.targetKubernetesClient.CoreV1().ConfigMaps("kube-system").Update(updated); err != nil {
```
Comment (ncdc) [inline pkg/upgrade/control_plane.go]: Can we Patch instead of Update? That might help with the v1beta1 vs v1beta2 issue?

File: pkg/upgrade/control_plane.go (hunk 3 above)
Comment (rudoi) [reply pkg/upgrade/control_plane.go]: I saw v1beta2 in my configmap so just went for that. will it work either way, you think?

Comment (rudoi) [reply pkg/upgrade/control_plane.go]: cc @chuckha

File: pkg/upgrade/control_plane.go (hunk 1 above)
Comment (amy) [reply pkg/upgrade/control_plane.go]: oh cool

File: pkg/upgrade/control_plane.go (hunk 3 above)
Comment (ncdc) [reply pkg/upgrade/control_plane.go]: I'd stick with v1beta1 if we can

File: pkg/upgrade/control_plane.go (hunk 6 above)
Comment (amy) [reply pkg/upgrade/control_plane.go]: Example of patch: https://github.com/vmware/cluster-api-upgrade-tool/blob/master/pkg/upgrade/machine_deployment.go#L139

Though, there's a github issue to swap the raw controller runtime patches with cluster-api patch helper: https://github.com/vmware/cluster-api-upgrade-tool/issues/83

I'm cool with either.

Comment (rudoi) [reply pkg/upgrade/control_plane.go]: I think we'd have to patch if we wanted v1beta1, because the configmap itself has v1beta2 in the ClusterStatus field.

I'll try a patch. Time to remember how patching works with clientsets! :D

Comment (ncdc) [reply pkg/upgrade/control_plane.go]: Oh it's encoded yaml inside the configmap. Hmm. Patch won't help w/that. But unstructured.Unstructured will.

Comment (ncdc) [reply pkg/upgrade/control_plane.go]: Or create a new go struct that has the json tags you need on it and use that instead of the one in kubeadm.

Comment (chuckha) [reply pkg/upgrade/control_plane.go]: we're already using Update in the codebase for other kubeadm config map manipulation: https://github.com/vmware/cluster-api-upgrade-tool/blob/master/pkg/upgrade/control_plane.go#L684

maybe best to keep them the same for now?

Comment (ncdc) [reply pkg/upgrade/control_plane.go]: Yes, Update is fine to keep. Sorry for the noise.

File: pkg/upgrade/control_plane.go (hunk 2 above)
Comment (detiber) [reply pkg/upgrade/control_plane.go]: :grimacing: should we track that as a separate issue?

File: pkg/upgrade/control_plane.go (hunk 3 above)
Comment (rudoi) [reply pkg/upgrade/control_plane.go]: so do we want to do some unstructured goodies here? or what do we think would be most appropriate?

also, so I'm understanding, is this just so we can avoid importing the extra package?

Comment (ncdc) [reply pkg/upgrade/control_plane.go]: Mostly future-proofing so we don't have to fix this in the future if the api version changes but the structure remains the same

**Comment by ncdc** [comment]
Woohoo CLA!

File: pkg/upgrade/control_plane.go [hunk 7]
```diff
@@ -681,6 +688,24 @@ func (u *ControlPlaneUpgrader) updateAndUploadKubeadmKubernetesVersion() error {
 	return nil
 }
 
+func (u *ControlPlaneUpgrader) removeNodeFromKubeadmConfigMap(nodeName string) error {
+	original, err := u.targetKubernetesClient.CoreV1().ConfigMaps("kube-system").Get("kubeadm-config", metav1.GetOptions{})
```
Comment (neolit123) [inline pkg/upgrade/control_plane.go]: ideally `metav1.NamespaceSystem` should be used instead of the literal.
`kubeadm-config` should be constant too.

File: pkg/upgrade/control_plane.go [hunk 8]
```diff
@@ -681,6 +688,24 @@ func (u *ControlPlaneUpgrader) updateAndUploadKubeadmKubernetesVersion() error {
...
+		return errors.Wrap(err, "error getting kubeadm configmap from target cluster")
+	}
+
+	updated, err := removeNodeFromClusterStatus(original, nodeName)
+	if err != nil {
+		return err
+	}
+
+	if _, err = u.targetKubernetesClient.CoreV1().ConfigMaps("kube-system").Update(updated); err != nil {
+		return errors.Wrap(err, "error updating kubeadm configmap")
```
Comment (neolit123) [inline pkg/upgrade/control_plane.go]: i would replace `configmap` with `ConfigMap` as per the sig-docs guide on API objects.

File: pkg/upgrade/control_plane.go [hunk 9]
```diff
@@ -700,3 +725,32 @@ func updateKubeadmKubernetesVersion(original *v1.ConfigMap, version string) (*v1
 
 	return cm, nil
 }
+
+func removeNodeFromClusterStatus(original *v1.ConfigMap, nodeName string) (*v1.ConfigMap, error) {
+	cm := original.DeepCopy()
+
+	clusterStatus := &unstructured.Unstructured{}
+	if err := yaml.Unmarshal([]byte(cm.Data["ClusterStatus"]), &clusterStatus); err != nil {
+		return nil, errors.Wrap(err, "error decoding kubeadm configmap ClusterStatus")
```
Comment (neolit123) [inline pkg/upgrade/control_plane.go]: `error decoding the kubeadm ClusterStatus object`?

File: pkg/upgrade/control_plane.go [hunk 10]
```diff
@@ -700,3 +725,32 @@ func updateKubeadmKubernetesVersion(original *v1.ConfigMap, version string) (*v1
...
+
+	delete(endpoints, nodeName)
+	err = unstructured.SetNestedMap(clusterStatus.UnstructuredContent(), endpoints, "apiEndpoints")
+	if err != nil {
+		return nil, err
+	}
+
+	updated, err := yaml.Marshal(clusterStatus)
+	if err != nil {
+		return nil, errors.Wrap(err, "error encoding kubeadm configmap ClusterConfiguration")
```
Comment (neolit123) [inline pkg/upgrade/control_plane.go]: `error encoding the kubeadm ClusterConfiguration object`?

File: pkg/upgrade/control_plane.go (hunk 7 above)
Comment (rudoi) [reply pkg/upgrade/control_plane.go]: i globally swapped this in (in this file), FYI

File: go.sum [hunk 11]
```diff
@@ -340,7 +340,6 @@ modernc.org/golex v1.0.0/go.mod h1:b/QX9oBD/LhixY6NDh+IdGv17hgB+51fET1i2kPSmvk=
 modernc.org/mathutil v1.0.0/go.mod h1:wU0vUrJsVWBZ4P6e7xtFJEhFSNsfRLJ8H458uRjg03k=
 modernc.org/strutil v1.0.0/go.mod h1:lstksw84oURvj9y3tn8lGvRxyRC1S2+g5uuIzNfIOBs=
 modernc.org/xc v1.0.0/go.mod h1:mRNCo0bvLjGhHO9WsyuKVU4q0ceiDDDoEeWDJHrNx8I=
-sigs.k8s.io/cluster-api v0.2.5 h1:N3nz2U62tE1lm4szCrEDMPMg/8RMiLaYgHWZJqkSuLE=
 sigs.k8s.io/cluster-api v0.2.5/go.mod h1:Agc72Ra5LMOkQQ2v/Ywv1KUemaYAwvkQ+G59Ym5H8e4=
```
Comment (vincepri) [inline go.sum]: This line should also get removed with `make module`

Comment (ncdc) [reply go.sum]: No - cabpk still uses v0.2.5 (we chatted on Slack about this)

File: pkg/upgrade/control_plane.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (ncdc) [reply pkg/upgrade/control_plane.go]: @rudoi feel like doing the nil check just to be safe?

File: go.sum (hunk 11 above)
Comment (vincepri) [reply go.sum]: ah gotcha, sounds good

File: pkg/upgrade/control_plane.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (rudoi) [reply pkg/upgrade/control_plane.go]: yep, no problem. missed this one.

File: go.sum (hunk 11 above)
Comment (rudoi) [reply go.sum]: ran `make modules`, no diff FYI

**Comment by rudoi** [comment]
@vincepri did I miss any? grabbed the nil check.

**Comment by vincepri** [comment]
that was the one!

**Comment by ncdc** [comment]
@rudoi could you please squash?

**Comment by rudoi** [comment]
> @rudoi could you please squash?

done
