### PR TITLE
Fall back to 127.0.0.1 in etcdctl commands when etcd pod has no IP

### LINKED ISSUE #161: etcd commands fail when the pod lacks an IP
When the etcd pod lacks an IP address, the commands to `etcdctl` will time out:

```
time="2020-04-16T22:02:43Z" level=info msg="Running etcdctl" args="member list -w json" pod=etcd-my-tkc-2-control-plane-66dc8
time="2020-04-16T22:02:46Z" level=info msg="etcdctl stdout: "
time="2020-04-16T22:02:46Z" level=info msg="etcdctl stderr: Error: context deadline exceeded\n"
command terminated with exit code 2
github.com/vmware/cluster-api-upgrade-tool/pkg/internal/kubernetes.PodExec
	/workspace/pkg/internal/kubernetes/pod_exec.go:63
Error: command terminated with exit code 2
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).etcdctlForPod
...
```

Admittedly it's a little weird that the etcd pod lacks an IP. This appears only to happen in our simulated environments where the nodes are running in a container and the pods are using `hostNetwork: true`. That said, falling back to `"[127.0.0.1]"` when the pod lacks an IP lets everything else continue to work as-expected.

### PR DESCRIPTION
**Pull request by tvs**
In certain environments the etcd pod will lack an IP address. When this
occurs, we can fall back on talking to the loopback address in the
etcdctl commands.

Fixes #161

### CODE REVIEW

File: pkg/upgrade/control_plane.go [hunk 1]
```diff
@@ -1182,7 +1182,11 @@ func (u *ControlPlaneUpgrader) etcdctl(ctx context.Context, args ...string) (str
 func (u *ControlPlaneUpgrader) etcdctlForPod(ctx context.Context, pod *v1.Pod, args ...string) (string, string, error) {
 	u.log.Info("Running etcdctl", "pod", pod.Name, "args", strings.Join(args, " "))
 
-	endpoint := fmt.Sprintf("https://%s:2379", pod.Status.PodIP)
+	ip := pod.Status.PodIP
+	if ip == "" {
+		ip = "[127.0.0.1]"
```
Comment (vincepri) [inline pkg/upgrade/control_plane.go:1187]: Is this the format the endpoint is expecting? With the square brackets around it?

Comment (tvs) [reply pkg/upgrade/control_plane.go:1187]: It actually works both ways. I wound up changing it to this based on the `etcdctl` command found in the liveness probe for the pod:

```
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt
          --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
          get foo
```

Comment (vincepri) [reply pkg/upgrade/control_plane.go:1187]: Got it, does `pod.Status.PodIP` also come in brackets? If not, I'd prefer to keep it consistent

Comment (tvs) [reply pkg/upgrade/control_plane.go:1187]: Fair point - it won't, no. I'll go ahead and tweak that.
