### PR TITLE
Edit kubeadm ConfigMap for control plane upgrades

### LINKED ISSUE #56: Control plane upgrades run the wrong images in the new machines
`kubeadm join` determines the container image tag for the static pod manifests from the kubeadm configmap in the cluster. We must modify this when upgrading, before we create any new machines.

### PR DESCRIPTION
**Pull request by ncdc**
When a new control plane node joins the cluster, it gets the version to
use as the image tag for the static pod manifests from the
kubeadm-config ConfigMap in the kube-system namespace. We must change
the ClusterConfiguration.kubernetesVersion to match the desired version,
then upload the updated ConfigMap before proceeding to create any new
machines.

Signed-off-by: Andy Goldstein <goldsteina@vmware.com>

Fixes #56

### CODE REVIEW

File: pkg/upgrade/control_plane.go [hunk 1]
```diff
@@ -11,6 +11,8 @@ import (
 	"strings"
 	"time"
 
+	"sigs.k8s.io/yaml"
+
```
Comment (chuckha) [inline pkg/upgrade/control_plane.go]: nit: we should probably pull in those hack/verify scripts that @neolit123 has been posting around to our new sig cluster lifecycle projects. They are actually really awesome to have!

File: pkg/upgrade/control_plane.go [hunk 2]
```diff
@@ -518,3 +524,41 @@ func (u *ControlPlaneUpgrader) etcdctlForPod(ctx context.Context, pod *v1.Pod, a
 
 	return stdout, stderr, err
 }
+
+func (u *ControlPlaneUpgrader) updateAndUploadKubeadmKubernetesVersion() error {
```
Comment (chuckha) [inline pkg/upgrade/control_plane.go]: Do you have any interest in pulling this kind of work out into its own struct, maybe a struct responsible for modifying the kubeadm config? I was thinking if we doin't want to run `kubeadm reset` on the actual nodes themselves we will have to modify the kubeadm config anyway. Might be good to have that struct and tests in place when we get around to fixing that bug as well.

but i could see it as being useful

I don't mind this though, I think this is clear enough

Comment (ncdc) [reply pkg/upgrade/control_plane.go]: I'd prefer to merge this as-is and open issue(s) as needed for future work, if that's ok with you?

File: pkg/upgrade/control_plane.go (hunk 1 above)
Comment (ncdc) [reply pkg/upgrade/control_plane.go]: Add an issue please?

File: pkg/upgrade/control_plane.go (hunk 2 above)
Comment (chuckha) [reply pkg/upgrade/control_plane.go]: definitely. Merging.
